### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by armintoepfer** [shounak1990/ChromaClique#2]
Hi!

If you blatantly copy/paste HaploClique and only modify minor parts, either fork it properly via github, so that the source is known, or at least add acknowledgements to all original authors, including Bernhard Lang, Marcel Meyerheim, and myself.

 - Armin

**Comment by tobiasmarschall** [comment]
Dear Armin,

no worries. I added a note and link to HaploClique. I agree that a fork would have been better.

Please note that the situation is the same as for HaploClique, which started off being based on code from Clever. Maybe you should consider referencing Clever from the HaploClique Readme. On this occasion, it might also be worth noting that Stefan (Canzar), who is part of the ChromaClique team, was also part of the team that developed Clever in the first place.

Best,
Tobias

**Comment by armintoepfer** [comment]
I agree! Have you copied CLEVER to GitHub, as http://clever-sv.googlecode.com/ is dead?

**Comment by tobiasmarschall** [comment]
Thanks. We moved to bitbucket when googlecode went down:
https://bitbucket.org/tobiasmarschall/clever-toolkit

**Comment by armintoepfer** [comment]
Done!
